# Generated by Django 6.0.4 on 2026-05-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0002_saveads_started_at_alter_saveads_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amont', models.IntegerField(default=0, editable=False)),
                ('swap_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('available_swaps', models.IntegerField(default=0, editable=False)),
                ('available_swaps_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.ads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
