# Generated by Django 6.0.4 on 2026-05-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swap', '0001_initial'),
        ('Task', '0002_saveads_started_at_alter_saveads_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='ads_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.saveads'),
        ),
    ]
