# Generated by Django 6.0.4 on 2026-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swap', '0002_swap_ads_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='usdt',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
