# Generated by Django 6.0.4 on 2026-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swap', '0003_swap_usdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='ad',
        ),
        migrations.AddField(
            model_name='swap',
            name='tax',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='swap',
            name='swap_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=2000000),
        ),
    ]
