# Generated by Django 6.0.4 on 2026-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swap', '0005_alter_swap_swap_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='swap_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
    ]
