# Generated by Django 6.0.4 on 2026-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Withdraw', '0002_withdraw_paid_at_withdraw_status_alter_withdraw_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='charge',
            field=models.IntegerField(default=1),
        ),
    ]
