# Generated by Django 6.0.4 on 2026-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_dayclam_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclam',
            name='clicks',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
