# Generated by Django 6.0.4 on 2026-05-20 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveads',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saveads',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
