# Generated by Django 6.0.4 on 2026-08-03 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_adview_userwallet_dailyadcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsview',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='adsview',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adsview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='adsview',
            name='ymid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='AdView',
        ),
    ]
